apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dev
  region: eu-central-1

nodeGroups:
  - name: nodes-general
    labels:
        role: workers
    instanceType: t2.small
    desiredCapacity: 1
    volumeSize: 20